services:
  api:
    container_name: api
    image: drglasdou/nest_gql:latest
    build:
      context: .
      dockerfile: dockerfile.prod
    restart: always
    env_file:
      - .env
    ports:
      - '8080:3000'
    depends_on:
      - pg
    networks:
      - pg-network
    healthcheck:
      test:
        ['CMD-SHELL', 'curl -f http://localhost:3000/api/v1/health || exit 1']
      interval: 30s
      timeout: 10s
      retries: 5

  pg:
    image: postgres:17.6
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - '5432:5432'
    networks:
      - pg-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${PG_USER}']
      interval: 10s
      timeout: 5s
      retries: 5

  pg_admin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - '5050:80'
    depends_on:
      - pg
    networks:
      - pg-network
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost/ || exit 1']
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  pg_data:

networks:
  pg-network:
    driver: bridge
