services:
  gql_template:
    container_name: gql_template
    image: drglasdou/nest-gql.glasdou:latest
    build:
      context: .
      dockerfile: dockerfile.prod
    restart: always
    env_file:
      - .env
    environment:
      PG_HOST: gql_template_pg
      REDIS_HOST: gql_template_redis
    ports:
      - "4000:4000"
    depends_on:
      gql_template_pg:
        condition: service_healthy
    networks:
      - gql_template_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4000/v1/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5