services:
  gql_template_name:
    build:
      context: .
      dockerfile: dockerfile.prod
    image: drglasdou/nest-gql.glasdou:${APP_VERSION:-1.0.0}

  gql_template_latest:
    build:
      context: .
      dockerfile: dockerfile.prod
    image: drglasdou/nest-gql.glasdou:latest